/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        // Pharma-professional palette
        pharma: {
          50: "#eff6ff",
          100: "#dbeafe",
          200: "#bfdbfe",
          300: "#93c5fd",
          400: "#60a5fa",
          500: "#3b82f6",
          600: "#2563eb",
          700: "#1d4ed8",
          800: "#1e40af",
          900: "#1e3a8a",
        },
        // Custom colors from temp HTML
        "surface-container-highest": "#d8e3fb",
        "tertiary-fixed-dim": "#c4c7c9",
        "surface-variant": "#d8e3fb",
        "on-tertiary-fixed-variant": "#444749",
        "secondary-fixed": "#93f2f2",
        "outline-variant": "#c2c6d3",
        "surface-container-high": "#dee8ff",
        "on-primary-container": "#b0ccff",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "surface-tint": "#175eae",
        "on-secondary-container": "#006e6e",
        "on-tertiary-fixed": "#191c1e",
        "secondary-fixed-dim": "#76d6d5",
        "error": "#ba1a1a",
        "surface": "#f9f9ff",
        "surface-bright": "#f9f9ff",
        "inverse-primary": "#a8c8ff",
        "secondary-container": "#90efef",
        "secondary": "#006a6a",
        "on-background": "#111c2d",
        "primary-fixed-dim": "#a8c8ff",
        "on-tertiary": "#ffffff",
        "surface-container": "#e7eeff",
        "on-surface": "#111c2d",
        "on-tertiary-container": "#c9cbcd",
        "inverse-on-surface": "#ecf1ff",
        "on-primary-fixed-variant": "#00468a",
        "on-secondary-fixed": "#002020",
        "primary": "#003e7b",
        "on-surface-variant": "#424751",
        "inverse-surface": "#263143",
        "on-primary-fixed": "#001b3c",
        "primary-fixed": "#d6e3ff",
        "outline": "#727783",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#535658",
        "on-secondary-fixed-variant": "#004f4f",
        "on-primary": "#ffffff",
        "surface-dim": "#cfdaf2",
        "on-error": "#ffffff",
        "primary-container": "#0055a5",
        "surface-container-low": "#f0f3ff",
        "background": "#f9f9ff",
        "tertiary": "#3c3f41",
        "tertiary-fixed": "#e0e3e5",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1280px",
        "unit": "8px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "margin-desktop": "48px"
      },
      fontFamily: {
        "body-md": ["Inter"],
        "body-sm": ["Inter"],
        "label-bold": ["Inter"],
        "h1": ["Manrope"],
        "body-lg": ["Inter"],
        "h3": ["Manrope"],
        "button": ["Manrope"],
        "h2": ["Manrope"]
      },
      fontSize: {
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "label-bold": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "h1": ["40px", { "lineHeight": "1.2", "fontWeight": "800" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "h3": ["24px", { "lineHeight": "1.4", "fontWeight": "700" }],
        "button": ["16px", { "lineHeight": "1", "fontWeight": "600" }],
        "h2": ["32px", { "lineHeight": "1.3", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
};
